### ISSUE TITLE
Improvement on OpenAPI with different servers

### ISSUE THREAD

**Issue by jacobhampel** [slinkydeveloper/vertx-web#4]
### Version

* vert.x core: 3.6.2
* vert.x web: 3.6.2

### Context
If I have defined multiple servers in the OpenAPI yaml file how can I set one of the servers in Vert.x?
For me, the use case is that I have servers with different base paths.
E.g.
localhost/vertx/...
github.com/rest/vertx

In the OpenAPI petstore example the base path would be "v1". Also for one server, the base path isn't used.

### Do you have a reproducer?

[Github test repro](https://github.com/jacobhampel/openapitest)

### Steps to reproduce

1. Simply run the with `gradle run` and point your web browser to localhost:8080/pets.
2. It prints the string "listPets"
3. Point the web browser to localhost:8080/v1/pets, which is correct according to the yaml file.

### Extra

* Anything that can be relevant

**Comment by slinkydeveloper** [comment]
Can you move to https://github.com/vert-x3/vertx-web/issues? This is my own fork.
btw you can set the base path just generating the router and mounting it as subrouter of another router. Example
```
Router generated = rf.getRouter()
Router main =...
main.mountSubRouter("/api", generated)
```
